version: "3.1"
services:
  finanzdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: finanz
    volumes:
      - ./Dockerdata/db:/var/lib/postgresql/data
