version: "3.1"
services:
  finanzdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finanz
    volumes:
      - ./DockerdataProd/db:/var/lib/postgresql/data

  finanz_backend:
    build:
      context: "./"
    restart: unless-stopped
    depends_on:
      - db1
    ports:
      - "4000:4000"
    links:
      - finanzdb
