version: "3.1"
services:
  finanzdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: finanz
    volumes:
      - ./DockerdataProd/db:/var/lib/postgresql/data

  finanz_backend:
    build:
      context: "./"
    restart: always
    depends_on:
      - finanzdb
    ports:
      - "4200:4000"
    links:
      - finanzdb

  dbbackups:
    image: kartoza/pg-backup
    volumes:
      - ./backupdb:/backups
    environment:
      - DUMPPREFIX=pgfinanz
      - POSTGRES_HOST=finanzdb
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin123
      - POSTGRES_PORT=5432
      - CRON_SCHEDULE="*/1 * * * *"
    restart: on-failure
    depends_on:
      finanzdb:
        condition: service_healthy
